### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by clery** [ChrisMiuchiz/CWSDK#2]
Hi there,

I'm just new to modding and I'm trying to understand what's going on.
I'm using your `Cube-World-Commands-Mod` as an example, but for now I'm not even sure how to compile all that.

Could you maybe add a small Readme to explain how to setup a basic environment to start modding ?

Any help would be appreciated !

**Comment by clery** [comment]
So, I figured out how to compile and stuff, so that's one thing.

So to try out how the SDK worked, I added a command to set my golds (nice right). But that was pretty easy. One thing I don't yet understand, is how did you manage to recreate the game data structures, and how you found what methods to export.

Could you maybe explain a little ?

PS: Thanks for the SDK and the mods you made, it's making my life a lot easier !

**Comment by coremaze** [comment]
This project is in the middle of a transition to Clang, but it should be easier to build mods with cwsdk once that's done.

Recreating game structures is done through reverse engineering the game's code and trying to assign meaningful names and structures to fields which exist.

The exported methods are picked up by the mod loader, so I know what methods to export because I made them exportable in the mod loader's.

**Comment by clery** [comment]
Alright thanks for the explanation ! I'll try to figure my way out a little to avoid bothering you too much.

I'm guessing that means I'll have to add stuff to the mod loader to handle new kinds of events

Also, about the reverse engineering part, are you using tools like Cheat Engine or should I look for something else ?

**Comment by coremaze** [comment]
Cheat Engine is a good debugger, but most reverse engineering happens in Hexray's IDA.

In addition, CWSDK now has a better readme, so your original issue should be addressed now.

**Comment by clery** [comment]
Perfect thanks for the Readme and tips on Hexray !
